AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: pseudo
    properties:
        pseudo:
            - NotBlank: ~
            - Type: string
        address:
            - Type: string
            - Optional:
              - NotBlank: false
